### ISSUE TITLE
DBIish

### ISSUE THREAD

**Issue by rbt** [Raku/ecosystem#596]
I'm not sure DBIish should be on the list. There are several people who work on that module on a regular basis.

Is there a benefit to moving it out of the raku-community-modules area?

**Comment by lizmat** [comment]
To me, the benefit would be that there's a single person responsible for the "architect" role, if you will.  I would also be fine with taking it off the list.

I see the "raku-community-modules" as a place where modules live that are not actively maintained.  Moving it out, would mean active maintenance.  Maybe my view of this is incorrect?

**Comment by jonathanstowe** [comment]
DBIish is a tricky one because there are several different knowledge domains in play, it needs people who know the supported databases well  as well as people who understand NativeCall and all the other things.  

The multi-skill thing could be addressed by splitting it up into a core module (with e.g. the SQLite driver,) and the individual drivers as separate modules with different maintainers, I've suggested this before but there wasn't any consensus on the matter.

There could be an argument made for sticking it in its own "Organisation" and adding all the current committers to that organisation I guess.

**Comment by rbt** [comment]
It's also too early to split it up as there are common API pieces which need to be defined, such as raku to database type coercions so that complex types (GIS features like Point or Line, or user custom types) can be round-tripped easily.

I don't mind creating a new Organization, but "Raku Community" seems like an equally good name for that organization.

**Comment by lizmat** [comment]
https://github.com/Raku/ecosystem/commit/76d73bda9b
